### ISSUE TITLE
Thanh Nguyen

### ISSUE THREAD

**Issue by thanhnguyen9** [tiy-houston-q4-rails/day-31#3]
https://candy-shop.herokuapp.com
default photo look crazy

**Comment by jwo** [comment]
Nicely done @thanhnguyentn 

Default photo is too big!

**Comment by Dwightgnjohnson** [comment]
Thanh you have to resize it yourself using something like preview... realized that once you left.

**Comment by thanhnguyen9** [comment]
Yeah man, i just remember that Jesse resized it by hand.
